const DISCORD_CONFIG_KEYS = {
  QUEST_ADMIN_ROLE: 'QUEST_ADMIN_ROLE',
  QUEST_TICKET_CATEGORY: 'QUEST_TICKET_CATEGORY',
  QUEST_ADMIN_PANEL_CHANNEL: 'QUEST_ADMIN_PANEL_CHANNEL',
  QUEST_REVIEW_CHANNEL: 'QUEST_REVIEW_CHANNEL',
  QUEST_TICKET_LOG_CHANNEL: 'QUEST_TICKET_LOG_CHANNEL',
  QUEST_ANNOUNCEMENT_CHANNEL: 'QUEST_ANNOUNCEMENT_CHANNEL',
  QUEST_SUBMISSION_LOG_CHANNEL: 'QUEST_SUBMISSION_LOG_CHANNEL',
  QUEST_LEGENDARY_CLAIM_CHANNEL: 'QUEST_LEGENDARY_CLAIM_CHANNEL',
  QUEST_SPECIAL_CHANNEL: 'QUEST_SPECIAL_CHANNEL',
  QUEST_LEGENDARY_CHANNEL: 'QUEST_LEGENDARY_CHANNEL',
  QUEST_PANEL: 'QUEST_PANEL',
  QUEST_PANEL_MESSAGE: 'QUEST_PANEL_MESSAGE'
};

module.exports = {
  DISCORD_CONFIG_KEYS
};
