const PROFESSIONS = {
  MEDIC: 'MEDIC',
  FARMER: 'FARMER',
  SOLDIER: 'SOLDIER',
  FISHER: 'FISHER',
  HUNTER: 'HUNTER',
  EXPLORER: 'EXPLORER',
  CHEF: 'CHEF',
  ENGINEER: 'ENGINEER',
  AVIATION: 'AVIATION'
};

const PROFESSION_LIST = Object.values(PROFESSIONS);

module.exports = {
  PROFESSIONS,
  PROFESSION_LIST
};
