const MAIN_QUEST_STATES = {
  LOCKED: 'LOCKED',
  AVAILABLE: 'AVAILABLE',
  PENDING_REVIEW: 'PENDING_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
};

const REPEATABLE_QUEST_STATES = {
  LOCKED: 'LOCKED',
  AVAILABLE: 'AVAILABLE',
  PENDING_REVIEW: 'PENDING_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  REJECTED: 'REJECTED',
  COOLDOWN: 'COOLDOWN'
};

const TIMED_QUEST_STATES = {
  NOT_OPEN: 'NOT_OPEN',
  AVAILABLE: 'AVAILABLE',
  PENDING_REVIEW: 'PENDING_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED'
};

const LEGENDARY_QUEST_STATES = {
  LOCKED: 'LOCKED',
  AVAILABLE: 'AVAILABLE',
  PENDING_REVIEW: 'PENDING_REVIEW',
  COMPLETED: 'COMPLETED',
  CLAIM_AVAILABLE: 'CLAIM_AVAILABLE',
  CLAIM_PENDING_REVIEW: 'CLAIM_PENDING_REVIEW',
  COOLDOWN: 'COOLDOWN'
};

const TICKET_STATES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_PLAYER: 'WAITING_PLAYER',
  WAITING_ADMIN: 'WAITING_ADMIN',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  CLOSED: 'CLOSED'
};

const STEP_STATES = {
  ACTIVE: 'ACTIVE',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

const SUBMISSION_STATES = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  CANCELLED: 'CANCELLED'
};

module.exports = {
  MAIN_QUEST_STATES,
  REPEATABLE_QUEST_STATES,
  TIMED_QUEST_STATES,
  LEGENDARY_QUEST_STATES,
  TICKET_STATES,
  STEP_STATES,
  SUBMISSION_STATES
};
